##  -*-  coding: utf-8; mode: ruby -*-  ##
##  vi: set ft=ruby

load  File.expand_path("DetectOS.rb")  if File.exists?("DetectOS.rb")

Vagrant.configure("2") do |config|
  config.vm.box = "takahiro-itou/centos8-develop"

  config.vm.provider "virtualbox" do |v|
    v.name   = "vagrant-centos8-develop"
    v.memory = "3072"

    v.gui    = false
    v.customize [
      "modifyvm",           :id,
      "--cableconnected1",  "on",
      "--hwvirtex",         "on",
      "--nestedpaging",     "on",
      "--largepages",       "on",
      "--ioapic",           "on",
      "--pae",              "on",
      "--paravirtprovider", "kvm",
    ]
  end

  config.vm.boot_timeout = 300

  config.vm.provision("file",
                      source: "../data/",
                      destination: "/tmp/")

    config.vm.provision("file",
                        source: "~/VagrantConfig/",
                        destination: "/tmp/")

  config.vm.provision("root", type: "shell",
                      path: "provision.root.sh",
                      privileged: true)
  config.vm.provision("user", type: "shell",
                      path: "provision.user.sh",
                      privileged: false)
  config.vm.synced_folder(".", "/vagrant", disabled: true)

end
