##  -*-  coding: utf-8; mode: ruby -*-  ##
##  vi: set ft=ruby

Vagrant.configure("2") do |config|
  config.vm.box = "takahiro-itou/centos8-develop"

  config.vm.provider "virtualbox" do |v|
    v.name   = "vagrant-centos8-develop"
    v.memory = "2048"

    v.gui    = false
    v.customize [
      "modifyvm",           :id,
      "--cableconnected1",  "on",
      "--hwvirtex",         "on",
      "--nestedpaging",     "on",
      "--largepages",       "on",
      "--ioapic",           "on",
      "--pae",              "on",
      "--paravirtprovider", "kvm",
    ]
  end

  config.vm.boot_timeout = 300

  config.vm.provision("root", type: "shell",
                      path: "provision.root.sh",
                      privileged: true)
  config.vm.synced_folder(".", "/vagrant", disabled: true)

end
